### ISSUE TITLE
Players not show

### ISSUE THREAD

**Issue by izzmatteo** [TGRHavoc/live_map-interface#82] opened 2021-09-06 03:09 UTC
Hello!
I configured everything according to the instructions and have the problem that the players are not displayed! You can see the normal blips! I don't see any mistakes myself either! Does anyone have an idea how I can fix this?

**Comment by TGRHavoc** [comment] 2021-09-06 08:22
Hey!

Please make sure you've read the resource's readme as well. Specifically the [How to install](https://github.com/TGRHavoc/live_map#how-to-install) section.

```
Now, you can enable the built-in client. Copy the example_client folder to client (this will allow you to update the resource without losing any changes to the client you make). Now, head on into the manifest file (fxmanifest.lua or whatever the latest version is called) and uncomment the client files.

client_script "client/*.lua"
 exports {
     "reverseWeaponHash", "reverseVehicleHash", "reverseStreetHash",
     "reverseZoneHash", "reverseAreaHash"
}
```

If it's still not working after this, if you could send me the URL of the interface so I could take a quick look.

**Comment by camonwii** [comment] 2021-09-07 03:01
Having the same issue again. Updated, changed the fxmanifest again and still no luck. Want me to email you again?

**Comment by TGRHavoc** [comment] 2021-09-07 07:54
Sure

**Comment by Flo122** [comment] 2021-09-29 18:51
Same Issue here

everything correct no players

**Comment by TGRHavoc** [comment] 2021-10-14 12:06
Closing as I cannot reproduce and it's been a while.

**Closed by TGRHavoc** 2021-10-14 12:06 UTC
