### ISSUE TITLE
4.1 Showing 2 users when only 1 online

### ISSUE THREAD

**Issue by scarecrow313** [TGRHavoc/live_map-interface#68] opened 2021-06-10 05:01 UTC
http://map.313eow.com/ - new version

http://map.313eow.com/2 - old version

same server. 

The new version is showing 2 users online when only myself is online. In the older version it doesnt show this.

**Comment by TGRHavoc** [comment] 2021-06-10 09:17
Have you modified "example_client" on the resource in anyway? If not, are you using the latest version of the resource?

I can't reproduce this, even the "getting in and out of vehicles" someone else was having.

https://images.tgrhavoc.co.uk/hades/anthropomorphic/0a8d6d7e1b49d0aebf3c301e043830758c68a6dd49289fd5e44e51ddc80f.gif

**Comment by TGRHavoc** [comment] 2021-06-17 14:51
@scarecrow313 any steps to help reproduce this issue? If not I'll have to consider it a non-bug and close this issue in a couple of days

**Closed** 2021-06-23 16:47 UTC
Labels: bug, needs repro
